spring:
    datasource:
        password: admin
        url: jdbc:mysql://localhost:3306/csvTutorialdb?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
